architect:
  - yegor256
docker:
  image: yegor256/rultor-image:1.13.0
install: |
  sudo apt-get install -y python3-pygments
  sudo pip3 install pygments
  pdd --file=/dev/null
merge:
  script: |
    latexmk -pdf
