docker:
  image: yegor256/rultor-image:1.22.0
install: |
  sudo tlmgr option repository ctan
  sudo tlmgr --verify-repo=none update --self
  sudo tlmgr --verify-repo=none install xstring totpages environ hyperxmp ifmtarg manyfoot
merge:
  script: |
    latexmk -pdf
