name: latexmk
on:
  push:
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y python3-pygments && sudo pip3 install pygments
      - run: sudo apt-get -y install ghostscript
      - uses: yegor256/latexmk-action@0.15.0
        with:
          opts: -pdf
          depends: DEPENDS.txt
      - run: |
          mkdir gh-pages
          cp main.pdf gh-pages
      - uses: JamesIves/github-pages-deploy-action@v4.7.2
        with:
          branch: gh-pages
          folder: gh-pages
          clean: false
